name: uu
on: [push]
jobs:
  u:
    name: u
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          #sudo su
          #apt install git
      - name: step2
        run: |
          sudo id
          
