name: ci
on: [push]
jobs:
  t:
    name: tt
    runs-on: [ubuntu-latest]
    steps:
      - name: ttt
        run: |
          echo "hello world"
          apt install git
      - name: tttt
        run: |
          echo "2"
